# Generated by Django 4.2 on 2023-10-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='knowledgebase',
            table='custom_knowledge_base_table',
        ),
    ]
